apiVersion: v1
kind: Service
metadata:
  name: ms2-backend
spec:
  selector:
    app: ms2-backend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms2-frontend
spec:
  selector:
    app: ms2-frontend
  ports:
    - port: 80
      targetPort: 80

