# Backend Node.js
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1-backend
  template:
    metadata:
      labels:
        app: ms1-backend
    spec:
      containers:
        - name: node-backend
          image: node-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-backend
spec:
  selector:
    app: ms1-backend
  ports:
    - port: 3000
      targetPort: 3000
---
# Redis
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1-redis
  template:
    metadata:
      labels:
        app: ms1-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-redis
spec:
  selector:
    app: ms1-redis
  ports:
    - port: 6379
---
# Frontend Nginx (dengan ConfigMap)
apiVersion: v1
kind: ConfigMap
metadata:
  name: ms1-index
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>MS1</title></head>
    <body style="background:#f0f0f0;text-align:center;padding:50px">
      <h1 style="color:#2196F3">Welcome to Microservice 1</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1-frontend
  template:
    metadata:
      labels:
        app: ms1-frontend
    spec:
      containers:
        - name: nginx
          image: nginx
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
          ports:
            - containerPort: 80
      volumes:
        - name: web-content
          configMap:
            name: ms1-index
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-frontend
spec:
  selector:
    app: ms1-frontend
  ports:
    - port: 80
      targetPort: 80
