apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1-redis
  template:
    metadata:
      labels:
        app: ms1-redis
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-redis
spec:
  selector:
    app: ms1-redis
  ports:
    - port: 6379
