apiVersion: v1
kind: Service
metadata:
  name: ms1-backend
spec:
  selector:
    app: ms1-backend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-frontend
spec:
  selector:
    app: ms1-frontend
  ports:
    - port: 80
      targetPort: 80
